### ISSUE TITLE
Angle build support for android ?

### ISSUE THREAD

**Issue by orosbogdan** [webrogue-runtime/angle-builder#1]
Can you add please suppor for android too ?

**Comment by Destructor17** [comment]
@orosbogdan I am sorry but Android and Linux already has OpenGL ES. Angle is used in webrogue  only when OpenGL ES is unavailable or depreciated. This issue will stay open because maybe I will eventually add support for Linux and Android to angle-builder

**Comment by Destructor17** [comment]
It looks like Google is intended to replace OpenGL ES drivers in Android with Angle in 2025, so I see no reason to build it. Issue closed
